###
POST http://localhost:8080/api/admin/login
Content-Type: application/json

{
  "username": "yiyangchen",
  "password": "597e86f4dc5fb25de4b53e13268b136c9dc2342db1f50a3d19046f20878ecd50"
}

###
POST http://localhost:8080/api/admin/getUserList
Content-Type: application/json

{
  "token": "eyJ6aXAiOiJHWklQIiwiYWxnIjoiSFM1MTIifQ.H4sIAAAAAAAA_6tWKi5NUrJSMjQwMjYwNDI2V9JRKi1OLfJLzE0FCldmVibmpSdnpOYBxQvKU8qAYmZJlkZmqUB-akWBkpWhuZmxobmhpbFlLQDdFImUTAAAAA.ko8wsI_HxM1VpsusOwxaqIE3D6YHKNMZgMwgmMGZKbdBmVJjUPwXprNzLIwT7eQqoWKM5gCoS77q01ErG356qg"
}

###
GET http://localhost:8080/api/query/getSearchType

###
POST http://localhost:8080/api/query/getBillList?searchType=DATE_RANGE
Content-Type: application/json

{
  "token": "eyJ6aXAiOiJHWklQIiwiYWxnIjoiSFM1MTIifQ.H4sIAAAAAAAA_xWLSQqAMAwA_5Kzhybdoo_wD22T3oRicQHx79bbzMA80I8MC5Ahj0gRLc6peM5SisscGNWqnV10QiHVChMcXfc1bTquH-1I7ZJzqEhQr8P1brBgDN4wR0PvB2I0xBtmAAAA.OIJ_8ZwmVVeAs1UAvX269L4_pfO9Lcq3vrzFuG_izhmY9i9BpHM0dwvuE4RUuPJ_puwYHG9OjkYxhTsDHhn4PQ",
  "page": 1,
  "limit": 10,
  "startDate": "2021-10-10",
  "endDate": "2025-10-11"
}

###
POST http://localhost:8080/api/user/register
Content-Type: application/json

{
  "username": "user1",
  "password": "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92"
}

###
POST http://localhost:8080/api/user/login
Content-Type: application/json

{
  "username": "user3",
  "password": "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92"
}

###
POST http://localhost:8080/api/user/initAccountInfo
Content-Type: application/json

{
  "token": "eyJ6aXAiOiJHWklQIiwiYWxnIjoiSFM1MTIifQ.H4sIAAAAAAAA_xWLSQqAMAwA_5KzhyRtU-sj_EMk6U0oiguIf7feZgbmgf1YYAJGTkScJYRKpjlwiZG0qhJyQExSWGo2GODYfZt19X79SD21y86uZuLJu_vdYKIskccyYnk_zDDYu2YAAAA.89cZi4EluO6jfUu5PO_CDb6qIp6gf6tNDvzGVWiCUP62Yci3C7zFpSfGC1ANDq58zqbcuy7tIvhZXI7e4pdZnQ",
  "account": "1234567890",
  "balance": 100000,
  "description": "建行卡"
}

###
POST http://localhost:8080/api/bill/addBill
Content-Type: application/json

{
  "token": "eyJ6aXAiOiJHWklQIiwiYWxnIjoiSFM1MTIifQ.H4sIAAAAAAAA_xWLSQqAMAwA_5KzhyRtU-sj_EMk6U0oiguIf7feZgbmgf1YYAJGTkScJYRKpjlwiZG0qhJyQExSWGo2GODYfZt19X79SD21y86uZuLJu_vdYKIskccyYnk_zDDYu2YAAAA.89cZi4EluO6jfUu5PO_CDb6qIp6gf6tNDvzGVWiCUP62Yci3C7zFpSfGC1ANDq58zqbcuy7tIvhZXI7e4pdZnQ",
  "recordEnum": "INCOME",
  "amount": 1000,
  "account": "1234567890",
  "type": "FOOD",
  "date": "2021-10-21",
  "remarks": "吃了顿美食",
  "userId": "",
  "id": 0
}

###
GET http://localhost:8080/api/bill/getRecordType

###
POST http://localhost:8080/api/bill/getBillList?page=1&limit=10&lastId=0
Content-Type: application/json

{
  "token": "eyJ6aXAiOiJHWklQIiwiYWxnIjoiSFM1MTIifQ.H4sIAAAAAAAA_xWLSQqAMAwA_5KzhyRtU-sj_EMk6U0oiguIf7feZgbmgf1YYAJGTkScJYRKpjlwiZG0qhJyQExSWGo2GODYfZt19X79SD21y86uZuLJu_vdYKIskccyYnk_zDDYu2YAAAA.89cZi4EluO6jfUu5PO_CDb6qIp6gf6tNDvzGVWiCUP62Yci3C7zFpSfGC1ANDq58zqbcuy7tIvhZXI7e4pdZnQ"
}

###
GET http://localhost:8080/api/bill/getTypeList

###
POST http://localhost:8080/api/query/getReport
Content-Type: application/json

{
    "token": "eyJ6aXAiOiJHWklQIiwiYWxnIjoiSFM1MTIifQ.H4sIAAAAAAAA_xWLQQ6AIAzA_rKzB7fBQB_hH4DNm4mRoCbGv4u3tkkfqC3DDDSSR6SAjFMqPmYtxeUoEY2NJxeckqR1hQFatWNJm_XrR-5pv_TsqirmrbvdO8wYxDMLk3s_4oRnJWYAAAA.z45FS1n-ERmaZ20mcIpvni7BB8fGbTO9cxyiqSMasFi58RxEpysHx4aJE-gZynipxqQfFuUjik2YdPQKznsfrw",
    "startDate": "2025-10-10",
    "endDate": "2025-10-10"
}

###
POST http://localhost:8080/api/user/getUserAccount
Content-Type: application/json

{
  "token": "eyJ6aXAiOiJHWklQIiwiYWxnIjoiSFM1MTIifQ.H4sIAAAAAAAA_xWLQQ6AIAzA_rKzBxgwhEf4B-bmzYRIUBPj38Vb26QPtM6QAQ0GizYlb3RjMrOy9yyxRGcs01ocSSgUYYLe9FjKruP60Y1ULzmHipAGHa53hWwjESZC794PQdILjWYAAAA.1lgzbkWPsFx5y-dA4tnTTHuZl_uHD6eWUvusmUuqbQoxWVPWBixYA6ChnqORtqnex0n8QxBGmeQacULMettCJg"
}

###
POST http://localhost:8080/api/user/login
Content-Type: application/json

{
  "username": "user3",
  "password": "8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92"
}
